// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Web.Data;

namespace Ventas.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200522031419_pedido")]
    partial class pedido
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Web.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Disponible");

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<string>("Nombre");

                    b.Property<decimal>("Precio");

                    b.Property<double>("Stock");

                    b.Property<string>("UltimaCompra");

                    b.Property<string>("UltimaVenta");

                    b.Property<int?>("UsuariosId");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ventas.Web.Data.Entities.DetallesPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cantidad");

                    b.Property<int?>("PedidoId");

                    b.Property<decimal>("Precio");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("Ventas.Web.Data.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DeliveryFecha");

                    b.Property<DateTime>("OrdenFecha");

                    b.Property<int>("UsuariosId");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Ventas.Web.Data.Entities.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido_Materno")
                        .IsRequired();

                    b.Property<string>("Apellido_Paterno")
                        .IsRequired();

                    b.Property<string>("Correo")
                        .HasMaxLength(100);

                    b.Property<string>("Direccion")
                        .HasMaxLength(100);

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Telefono")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Shop.Web.Data.Entities.Product", b =>
                {
                    b.HasOne("Ventas.Web.Data.Entities.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId");
                });

            modelBuilder.Entity("Ventas.Web.Data.Entities.DetallesPedido", b =>
                {
                    b.HasOne("Ventas.Web.Data.Entities.Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId");

                    b.HasOne("Shop.Web.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ventas.Web.Data.Entities.Pedido", b =>
                {
                    b.HasOne("Ventas.Web.Data.Entities.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
